// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8qXbIDPBFgwetDShTEJa6r-jD74QkEHE',
    appId: '1:1095633211557:web:a1849e8f478d8721a8bd4c',
    messagingSenderId: '1095633211557',
    projectId: 'bicycle2023-12b80',
    authDomain: 'bicycle2023-12b80.firebaseapp.com',
    storageBucket: 'bicycle2023-12b80.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMHe6Ij5Xnju1OavrKERqDkQvlCww81v0',
    appId: '1:1095633211557:android:e079a863ceb7c544a8bd4c',
    messagingSenderId: '1095633211557',
    projectId: 'bicycle2023-12b80',
    storageBucket: 'bicycle2023-12b80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ5FbXmVSqZAabEmv9WIcrfmXnX3gNr4A',
    appId: '1:1095633211557:ios:aaf6bf31e3958994a8bd4c',
    messagingSenderId: '1095633211557',
    projectId: 'bicycle2023-12b80',
    storageBucket: 'bicycle2023-12b80.firebasestorage.app',
    iosBundleId: 'com.example.smartrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ5FbXmVSqZAabEmv9WIcrfmXnX3gNr4A',
    appId: '1:1095633211557:ios:aaf6bf31e3958994a8bd4c',
    messagingSenderId: '1095633211557',
    projectId: 'bicycle2023-12b80',
    storageBucket: 'bicycle2023-12b80.firebasestorage.app',
    iosBundleId: 'com.example.smartrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8qXbIDPBFgwetDShTEJa6r-jD74QkEHE',
    appId: '1:1095633211557:web:07e070c6de2f902fa8bd4c',
    messagingSenderId: '1095633211557',
    projectId: 'bicycle2023-12b80',
    authDomain: 'bicycle2023-12b80.firebaseapp.com',
    storageBucket: 'bicycle2023-12b80.firebasestorage.app',
  );
}
